services:
  app:
    image: ghcr.io/2086316487/infinite-canvas:latest
    container_name: infinite-canvas
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    restart: unless-stopped
